import { createClient } from '@/lib/supabase/server'
import { redirect, notFound } from 'next/navigation'
import Link from 'next/link'
import { PrintButton } from './print-button'

export default async function CaseReportPage({
  params
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: caseData } = await supabase
    .from('verification_cases')
    .select(`
      id, status, check_type, created_at, updated_at,
      candidates ( full_name, phone, email ),
      employers ( name, hr_contact_name, hr_contact_phone ),
      clients ( company_name )
    `)
    .eq('id', id)
    .single()

  if (!caseData) notFound()

  const { data: verifiedLog } = await supabase
    .from('call_logs')
    .select('*')
    .eq('case_id', id)
    .not('extracted_data', 'is', null)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  const candidate = caseData.candidates as any
  const employer = caseData.employers as any
  const client = caseData.clients as any
  const extracted = verifiedLog?.extracted_data as Record<string, unknown> | undefined

  const fieldLabels: Record<string, string> = {
    job_title: 'Job title',
    start_date: 'Employment start date',
    end_date: 'Employment end date',
    reason_for_leaving_category: 'Reason for leaving',
    would_rehire: 'Would rehire',
    salary_confirmed: 'Salary confirmed',
    confidence: 'Confidence score',
    notes: 'Notes'
  }

  return (
    <div className="max-w-2xl mx-auto p-8">
      <div className="flex items-center justify-between mb-6 print:hidden">
        <Link href={`/dashboard/cases/${id}`} className="text-sm text-gray-500">
          &larr; Back to case
        </Link>
        <PrintButton />
      </div>

      {caseData.status !== 'verified' && (
        <p className="text-sm text-orange-600 bg-orange-50 border border-orange-200 rounded p-3 mb-6 print:hidden">
          This case is not yet fully verified (current status: {caseData.status}). This report
          reflects the most recent data available and may be incomplete.
        </p>
      )}

      <div className="border-b pb-4 mb-6">
        <h1 className="text-2xl font-semibold">Employment Verification Report</h1>
        <p className="text-sm text-gray-500">Callibr — Background Verification Services</p>
      </div>

      <div className="grid grid-cols-2 gap-6 mb-6">
        <div>
          <h2 className="text-xs uppercase tracking-wide text-gray-500 mb-1">Candidate</h2>
          <p className="font-medium">{candidate?.full_name}</p>
          <p className="text-sm text-gray-600">{candidate?.phone}</p>
        </div>
        <div>
          <h2 className="text-xs uppercase tracking-wide text-gray-500 mb-1">Employer verified</h2>
          <p className="font-medium">{employer?.name}</p>
          <p className="text-sm text-gray-600">Contact: {employer?.hr_contact_name || 'N/A'}</p>
        </div>
        <div>
          <h2 className="text-xs uppercase tracking-wide text-gray-500 mb-1">Requested by</h2>
          <p className="text-sm">{client?.company_name}</p>
        </div>
        <div>
          <h2 className="text-xs uppercase tracking-wide text-gray-500 mb-1">Report date</h2>
          <p className="text-sm">{new Date(caseData.updated_at).toLocaleDateString()}</p>
        </div>
      </div>

      <div className="border rounded p-4 mb-6">
        <h2 className="text-sm font-semibold mb-3">Verification Findings</h2>

        {!extracted && (
          <p className="text-sm text-gray-500">No verification data available yet.</p>
        )}

        {extracted && (
          <table className="w-full text-sm">
            <tbody>
              {Object.entries(fieldLabels).map(([key, label]) =>
                extracted[key] !== undefined && extracted[key] !== null ? (
                  <tr key={key} className="border-t">
                    <td className="py-2 pr-4 text-gray-500 whitespace-nowrap">{label}</td>
                    <td className="py-2">{String(extracted[key])}</td>
                  </tr>
                ) : null
              )}
            </tbody>
          </table>
        )}
      </div>

      <p className="text-xs text-gray-400">
        This report was generated by Callibr's AI-assisted verification process based on a
        direct phone conversation with the listed employer contact. Findings reflect information
        provided verbally by the contacted party at the time of the call.
      </p>
    </div>
  )
}
